In [21]:
import numpy as np
X=2*np.random.rand(100,1)
y = 4 + 3*X + np.random.randn(100, 1)

In [22]:
X_b = np.c_[np.ones((100, 1)), X]

In [23]:
theta_hat = np.linalg.inv(X_b.T@X_b)@X_b.T@y

In [24]:
theta_hat

array([[3.77625566],
       [3.1711975 ]])

In [25]:
eta = 0.1
max_iter = 1000
m = 100

In [26]:
theta = np.random.rand(2,1)

In [27]:
for k in range(max_iter):
    gradients = 2/m*X_b.T@(X_b@theta-y)
    theta = theta - eta*gradients

In [28]:
theta

array([[3.77625566],
       [3.1711975 ]])

In [29]:
X_b

array([[1.        , 1.01366034],
       [1.        , 1.11800707],
       [1.        , 1.89034142],
       [1.        , 1.95995732],
       [1.        , 1.25142973],
       [1.        , 1.66813782],
       [1.        , 1.49226061],
       [1.        , 1.56635157],
       [1.        , 0.77124532],
       [1.        , 1.56511691],
       [1.        , 1.46022577],
       [1.        , 1.14200047],
       [1.        , 1.98410094],
       [1.        , 1.38556401],
       [1.        , 1.15744423],
       [1.        , 0.76160222],
       [1.        , 1.74054703],
       [1.        , 1.9286219 ],
       [1.        , 0.51440389],
       [1.        , 1.73259245],
       [1.        , 0.30930194],
       [1.        , 0.3926422 ],
       [1.        , 1.89979621],
       [1.        , 0.40370331],
       [1.        , 1.46556627],
       [1.        , 0.01454413],
       [1.        , 1.70421233],
       [1.        , 0.43874696],
       [1.        , 0.59239668],
       [1.        , 0.61784566],
       [1.

In [30]:
X_b[2:3]

array([[1.        , 1.89034142]])

In [31]:
y

array([[ 5.9299136 ],
       [ 7.50264619],
       [10.43433923],
       [10.1121172 ],
       [ 8.45612302],
       [ 7.63829082],
       [ 8.05998388],
       [ 9.51873042],
       [ 5.37492412],
       [ 9.14988471],
       [ 7.72903425],
       [ 7.17447644],
       [10.0162487 ],
       [ 7.56828681],
       [ 5.3818894 ],
       [ 5.20564525],
       [10.51213933],
       [10.23285145],
       [ 6.61314208],
       [ 9.62055228],
       [ 4.21015682],
       [ 5.24368853],
       [10.00235928],
       [ 4.29934751],
       [ 7.25815831],
       [ 3.37048576],
       [ 9.24732354],
       [ 4.4528607 ],
       [ 3.93804978],
       [ 5.66085749],
       [ 4.68178637],
       [ 6.62979244],
       [ 5.86192134],
       [ 4.63858107],
       [ 2.31005009],
       [ 6.73479404],
       [ 5.78365587],
       [12.21354321],
       [ 4.97317137],
       [ 7.11756499],
       [ 7.43158637],
       [ 5.80839439],
       [ 4.77087847],
       [ 5.65503057],
       [ 9.07254987],
       [ 6

In [32]:
y[2:3]

array([[10.43433923]])

In [33]:
np.random.randint(100)

39

In [34]:
epoch = 50
t0 = 5
t1 = 50

In [35]:
theta = np.random.randn(2,1)

In [56]:
for k in range(epoch):
    for i in range(m):
        random_index = np.random.randint(m)
        xi = X_b[random_index:random_index+1]
        yi = y[random_index:random_index+1]
        gradients = 2*xi.T*(xi@theta-yi)
        eta = 5/(50+k*m+i)
        theta = theta - eta*gradients

In [57]:
theta

array([[3.7521117 ],
       [3.17389423]])

In [38]:
y.ravel()

array([ 5.9299136 ,  7.50264619, 10.43433923, 10.1121172 ,  8.45612302,
        7.63829082,  8.05998388,  9.51873042,  5.37492412,  9.14988471,
        7.72903425,  7.17447644, 10.0162487 ,  7.56828681,  5.3818894 ,
        5.20564525, 10.51213933, 10.23285145,  6.61314208,  9.62055228,
        4.21015682,  5.24368853, 10.00235928,  4.29934751,  7.25815831,
        3.37048576,  9.24732354,  4.4528607 ,  3.93804978,  5.66085749,
        4.68178637,  6.62979244,  5.86192134,  4.63858107,  2.31005009,
        6.73479404,  5.78365587, 12.21354321,  4.97317137,  7.11756499,
        7.43158637,  5.80839439,  4.77087847,  5.65503057,  9.07254987,
        6.08725441,  9.27268106,  9.64404367,  4.43882602, 10.27471321,
        9.25957006,  9.5491294 ,  6.94927895,  8.05167768,  4.16246302,
        8.87559384, 10.1913023 ,  5.56040581,  5.83092879,  7.7738932 ,
        5.83163943,  5.43899086,  8.54864272,  6.99147946,  8.05666906,
        3.25285672,  7.37448562,  7.41521616,  7.32248228,  7.71

In [39]:
from sklearn.linear_model import SGDRegressor

In [42]:
sgd_reg = SGDRegressor(max_iter=1000, tol=1e-3, penalty=None, eta0=0.1)

In [44]:
sgd_reg.fit(X, y.ravel())

SGDRegressor(eta0=0.1, penalty=None)

In [45]:
sgd_reg.intercept_

array([3.72318361])

In [46]:
sgd_reg.coef_

array([3.15542615])

In [51]:
epoch = 50
minibatch_size = 20

In [54]:
theta = np.random.randn(2,1)
t=0
for k in range(epoch):
    shuffled_indices = np.random.permutation(m)
    X_b_shuffled = X_b[shuffled_indices]
    y_shuffled = y[shuffled_indices]
    for i in range(0, m, minibatch_size):
        t += 1
        xi = X_b_shuffled[i:i+minibatch_size]
        yi = y_shuffled[i:i+minibatch_size]
        gradients = 2/minibatch_size*xi.T@(xi@theta-yi)
        eta = 10/(100+t)
        theta = theta - eta*gradients

In [55]:
theta

array([[3.77767258],
       [3.17856902]])